manifest:
  version: '0.10'
  remotes:
  - name: github_origin
    url-base: https://github.com/TexasInstruments/
  - name: freertos
    url-base: https://github.com/FreeRTOS/
  - name: lwip
    url-base: https://git.savannah.gnu.org/git/
  - name: mbedtls
    url-base: https://github.com/Mbed-TLS/
  projects:
  - name: processor-sdk-mcu/mcupsdk_setup
    path: mcupsdk_setup
    remote: github_origin
    revision: k3_main
  - name: processor-sdk-mcu/mcu_plus_sdk
    path: mcu_plus_sdk
    remote: github_origin
    revision: k3_next
  - name: processor-sdk-mcu/freertos_fat
    path: mcu_plus_sdk/source/fs/freertos_fat/FreeRTOS-FAT
    remote: github_origin
    revision: refs/tags/MCUSDK_V1.1.0_MAIN
  - name: processor-sdk-mcu/freertos_kernel
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-Kernel
    remote: github_origin
    revision: refs/tags/V11.1.0
  - name: processor-sdk-mcu/freertos_posix
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-POSIX
    remote: github_origin
    revision: refs/tags/MCUSDK_V1.0.0
  - name: sysfw/rm_pm_hal
    path: mcu_plus_sdk/source/drivers/device_manager/rm_pm_hal/rm_pm_hal_src
    remote: github_origin
    revision: refs/tags/v11.00.07
  - name: sitmpusw/dmautils
    path: mcu_plus_sdk/source/drivers/dmautils
    remote: github_origin
    revision: master
  - name: mcupsdk-enet-lld
    path: mcu_plus_sdk/source/networking/enet/core
    remote: github_origin
    revision: mcupsdk_next
  - name: ethernet-rtos-drivers
    path: mcu_plus_sdk/source/board/ethphy/enet
    remote: github_origin
    revision: refs/tags/v2024.04
  - name: PSDKLA/k3-resource-partitioning
    path: mcu_plus_sdk/tools/sysfw/k3-resource-partitioning
    remote: github_origin
    revision: refs/tags/REL.MCUSDK.09.02.00.04
  - name: processor-sdk-mcu/mcupsdk_internal
    path: mcupsdk_internal
    remote: github_origin
    revision: k3_main
  - name: processor-sdk/safety_checkers
    path: mcu_plus_sdk/source/safety_checkers
    remote: github_origin
    revision: master
  - name: mbedtls
    path: mcu_plus_sdk/source/networking/mbedtls_library/mbedtls
    remote: mbedtls
    revision: refs/tags/mbedtls-2.13.1
  - name: lwip
    path: mcu_plus_sdk/source/networking/lwip/lwip-stack
    remote: lwip
    revision: refs/tags/STABLE-2_2_0_RELEASE
