manifest:
  version: '0.10'
  remotes:
  - name: origin
    url-base: https://github.com/TexasInstruments/
  - name: lwip
    url-base: https://github.com/lwip-tcpip/
  - name: mbedtls
    url-base: https://github.com/Mbed-TLS/
  - name: threadx
    url-base: https://github.com/eclipse-threadx/
  projects:
  - name: mcupsdk-setup
    path: mcupsdk_setup
    remote: origin
    revision: k3_main
  - name: mcupsdk-core-k3
    path: mcu_plus_sdk
    remote: origin
    revision: k3_next
  - name: mcupsdk-rm-pm-hal
    path: mcu_plus_sdk/source/drivers/device_manager/rm_pm_hal/rm_pm_hal_src
    remote: origin
    revision: refs/tags/v11.00.07
  - name: mcupsdk-dmautils
    path: mcu_plus_sdk/source/drivers/dmautils
    remote: origin
    revision: master
  - name: filex
    path: mcu_plus_sdk/source/fs/filex/filex_src
    remote: threadx
    revision: refs/tags/v6.4.1_rel
  - name: mcupsdk-FreeRTOS-FAT
    path: mcu_plus_sdk/source/fs/freertos_fat/FreeRTOS-FAT
    remote: origin
    revision: refs/tags/MCUSDK_V1.1.0_MAIN
  - name: mcupsdk-FreeRTOS-Kernel
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-Kernel
    remote: origin
    revision: refs/tags/V11.1.0
  - name: mcupsdk-FreeRTOS-Posix
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-POSIX
    remote: origin
    revision: refs/tags/MCUSDK_V1.0.0_MAIN
  - name: threadx
    path: mcu_plus_sdk/source/kernel/threadx/threadx_src
    remote: threadx
    revision: refs/tags/v6.4.1_rel
  - name: proc-safety-checkers
    path: mcu_plus_sdk/source/safety_checkers
    remote: origin
    revision: master
