manifest:
  projects:
  - name: mcupsdk-core
    path: mcu_plus_sdk
    remote: origin
    repo-path: mcupsdk-core
    revision: next
  - name: mcupsdk-setup
    path: mcupsdk_setup
    remote: origin
    repo-path: mcupsdk-setup
    revision: next
  - name: mcupsdk-FreeRTOS-Kernel
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-Kernel
    remote: origin
    repo-path: mcupsdk-FreeRTOS-Kernel
    revision: refs/tags/MCUSDK_V11.1.0_MAIN
  - name: mcupsdk-FreeRTOS-Kernel:V202110.00-SMP
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-Kernel-smp
    remote: origin
    repo-path: mcupsdk-FreeRTOS-Kernel
    revision: refs/tags/V202110.00-SMP
  - name: mcupsdk-FreeRTOS-Posix
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-POSIX
    remote: origin
    repo-path: mcupsdk-FreeRTOS-Posix
    revision: refs/tags/MCUSDK_V1.0.0_MAIN
  - name: mcupsdk-enet-lld
    path: mcu_plus_sdk/source/networking/enet/core
    remote: origin
    repo-path: mcupsdk-enet-lld
    revision: mcupsdk_next
  - name: mcupsdk-FreeRTOS-FAT
    path: mcu_plus_sdk/source/fs/freertos_fat/FreeRTOS-FAT
    remote: origin
    repo-path: mcupsdk-FreeRTOS-FAT
    revision: refs/tags/MCUSDK_V1.0.0_MAIN
  - name: mcupsdk-littlefs
    path: mcu_plus_sdk/source/fs/littlefs/LittleFS
    remote: origin
    repo-path: mcupsdk-littlefs
    revision: refs/tags/MCUSDK_V1.0.0_MAIN
  - name: lwip
    path: mcu_plus_sdk/source/networking/lwip/lwip-stack
    remote: lwip
    repo-path: lwip
    revision: refs/tags/STABLE-2_2_0_RELEASE
  - name: tinyusb
    path: mcu_plus_sdk/source/usb/tinyusb/tinyusb-stack
    remote: tinyusb
    repo-path: tinyusb
    revision: refs/tags/0.14.0
  - name: mcupsdk-cmsis
    path: mcu_plus_sdk/source/cmsis
    remote: origin
    repo-path: mcupsdk-cmsis
    revision: main
  - name: mbedtls
    path: mcu_plus_sdk/source/networking/mbedtls_library/mbedtls
    remote: mbedtls
    repo-path: mbedtls
    revision: refs/tags/mbedtls-2.13.1
  - name: enet-tsn-stack
    path: mcu_plus_sdk/source/networking/tsn/tsn-stack
    remote: origin
    repo-path: enet-tsn-stack
    revision: next
  - name: multicore-elf
    path: mcu_plus_sdk/tools/boot/multicore-elf
    remote: origin
    repo-path: multicore-elf
    revision: main
  - name: mcupsdk-sysconfig
    path: mcu_plus_sdk/source/sysconfig
    remote: origin
    repo-path: mcupsdk-sysconfig
    revision: next
  - name: tifs-mcu-common
    path: mcu_plus_sdk/source/security/security_common
    remote: origin
    repo-path: tifs-mcu-common
    revision: next
  - name: ethernet-rtos-drivers
    path: mcu_plus_sdk/source/board/ethphy/enet
    remote: origin
    repo-path: ethernet-rtos-drivers
    revision: refs/tags/v2024.04
  - name: ti-pmic-lld
    path: mcu_plus_sdk/source/board/pmic/pmic_lld/blackbird
    remote: origin
    repo-path: ti-pmic-lld
    revision: device/blackbird
  - name: ti-pmic-lld:derby
    path: mcu_plus_sdk/source/board/pmic/pmic_lld/derby
    remote: origin
    repo-path: ti-pmic-lld
    revision: device/derby
  remotes:
  - name: comm
    url-base: ssh://git@bitbucket.itg.ti.com/
  - name: origin
    url-base: https://github.com/TexasInstruments/
  - name: freertos
    url-base: https://github.com/FreeRTOS/
  - name: lwip
    url-base: https://git.savannah.gnu.org/git/
  - name: tinyusb
    url-base: https://github.com/hathach/
  - name: armmbed
    url-base: https://github.com/ARMmbed/
  - name: mbedtls
    url-base: https://github.com/Mbed-TLS/
