manifest:
  version: '0.10'
  projects:
  - name: mcupsdk-setup
    path: mcupsdk_setup
    url: https://github.com/TexasInstruments/mcupsdk-setup
    revision: k3_main
  - name: mcupsdk-core-k3
    path: mcu_plus_sdk
    url: https://github.com/TexasInstruments/mcupsdk-core-k3
    revision: k3_next
  - name: mcupsdk-coremark-pro
    path: mcu_plus_sdk/examples/benchmarks/coremark_pro_benchmark/coremark-pro
    url: https://github.com/TexasInstruments/mcupsdk-coremark-pro
    revision: refs/tags/MCUSDK_V1.0.0_MAIN
  - name: trusted-firmware-a
    path: mcu_plus_sdk/source/atf/trusted-firmware-a
    url: https://github.com/TrustedFirmware-A/trusted-firmware-a
    revision: 58b25570c9ef91753b14c2103f45f4be9dddb696
  - name: ethernet-rtos-drivers
    path: mcu_plus_sdk/source/board/ethphy/enet
    url: https://github.com/TexasInstruments/ethernet-rtos-drivers
    revision: refs/tags/v2025.03.5
  - name: ti-pmic-lld
    path: mcu_plus_sdk/source/board/pmic/pmic_lld
    url: https://github.com/TexasInstruments/ti-pmic-lld
    revision: refs/tags/REL.PMIC.TPS6522X.00.10.01
  - name: mcupsdk-cmsis
    path: mcu_plus_sdk/source/cmsis
    url: https://github.com/TexasInstruments/mcupsdk-cmsis
    revision: main
  - name: mcupsdk-rm-pm-hal
    path: mcu_plus_sdk/source/drivers/device_manager/rm_pm_hal/rm_pm_hal_src
    url: https://github.com/TexasInstruments/mcupsdk-rm-pm-hal
    revision: refs/tags/v11.02.09
  - name: mcupsdk-dmautils
    path: mcu_plus_sdk/source/drivers/dmautils
    url: https://github.com/TexasInstruments/mcupsdk-dmautils
    revision: master
  - name: filex
    path: mcu_plus_sdk/source/fs/filex/filex_src
    url: https://github.com/eclipse-threadx/filex
    revision: refs/tags/v6.4.1_rel
  - name: levelx
    path: mcu_plus_sdk/source/fs/filex/levelx_src
    url: https://github.com/eclipse-threadx/levelx
    revision: refs/tags/v6.4.1_rel
  - name: mcupsdk-FreeRTOS-FAT
    path: mcu_plus_sdk/source/fs/freertos_fat/FreeRTOS-FAT
    url: https://github.com/TexasInstruments/mcupsdk-FreeRTOS-FAT
    revision: refs/tags/MCUSDK_V1.1.0_MAIN
  - name: mcupsdk-FreeRTOS-Kernel
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-Kernel
    url: https://github.com/TexasInstruments/mcupsdk-FreeRTOS-Kernel
    revision: refs/tags/V11.1.0
  - name: mcupsdk-FreeRTOS-Posix
    path: mcu_plus_sdk/source/kernel/freertos/FreeRTOS-POSIX
    url: https://github.com/TexasInstruments/mcupsdk-FreeRTOS-Posix
    revision: refs/tags/MCUSDK_V1.0.0_MAIN
  - name: threadx
    path: mcu_plus_sdk/source/kernel/threadx/threadx_src
    url: https://github.com/eclipse-threadx/threadx
    revision: refs/tags/v6.4.1_rel
  - name: mcupsdk-enet-lld
    path: mcu_plus_sdk/source/networking/enet/core
    url: https://github.com/TexasInstruments/mcupsdk-enet-lld
    revision: mcupsdk_next
  - name: enet-firmware
    path: mcu_plus_sdk/source/networking/ethfw
    url: https://github.com/TexasInstruments/enet-firmware
    revision: master
  - name: lwip
    path: mcu_plus_sdk/source/networking/lwip/lwip-stack
    url: https://github.com/lwip-tcpip/lwip
    revision: refs/tags/STABLE-2_2_1_RELEASE
  - name: mbedtls
    path: mcu_plus_sdk/source/networking/mbedtls_library/mbedtls
    url: https://github.com/Mbed-TLS/mbedtls
    revision: refs/tags/mbedtls-2.13.1
  - name: netxduo
    path: mcu_plus_sdk/source/networking/netxduo/netxduo_src
    url: https://github.com/eclipse-threadx/netxduo
    revision: refs/tags/v6.4.1_rel
  - name: enet-tsn-stack
    path: mcu_plus_sdk/source/networking/tsn/tsn-stack
    url: https://github.com/TexasInstruments/enet-tsn-stack
    revision: next
  - name: proc-safety-checkers
    path: mcu_plus_sdk/source/safety_checkers
    url: https://github.com/TexasInstruments/proc-safety-checkers
    revision: refs/tags/SITARA.RM.PM.11.02.00.00
  - name: multicore-elf
    path: mcu_plus_sdk/tools/boot/multicoreELFImageGen/
    url: https://github.com/TexasInstruments/multicore-elf
    revision: refs/tags/MCUSDK_K3_V1.0.0
  - name: proc-ospi-tuning
    path: mcu_plus_sdk/source/drivers/ospi/v0/ospi_tuning
    url: https://github.com/TexasInstruments/proc-ospi-tuning
    revision: refs/tags/MCUSDK_V2.0.0_MAIN
